#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CircularGauge.Resource", IsApplication=true)]

namespace CircularGauge
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Syncfusion.Gauges.Resource.Attribute.barPointerColor = global::CircularGauge.Resource.Attribute.barPointerColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.barPointerCornerRadius = global::CircularGauge.Resource.Attribute.barPointerCornerRadius;
			global::Com.Syncfusion.Gauges.Resource.Attribute.barPointerCornerRadiusType = global::CircularGauge.Resource.Attribute.barPointerCornerRadiusType;
			global::Com.Syncfusion.Gauges.Resource.Attribute.barPointerStrokeWidth = global::CircularGauge.Resource.Attribute.barPointerStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.barPointerValue = global::CircularGauge.Resource.Attribute.barPointerValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.characterHeight = global::CircularGauge.Resource.Attribute.characterHeight;
			global::Com.Syncfusion.Gauges.Resource.Attribute.characterSpacing = global::CircularGauge.Resource.Attribute.characterSpacing;
			global::Com.Syncfusion.Gauges.Resource.Attribute.characterStrokeColor = global::CircularGauge.Resource.Attribute.characterStrokeColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.characterType = global::CircularGauge.Resource.Attribute.characterType;
			global::Com.Syncfusion.Gauges.Resource.Attribute.characterWidth = global::CircularGauge.Resource.Attribute.characterWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularGaugeScaleDirection = global::CircularGauge.Resource.Attribute.circularGaugeScaleDirection;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleInterval = global::CircularGauge.Resource.Attribute.circularScaleInterval;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleLabelOffset = global::CircularGauge.Resource.Attribute.circularScaleLabelOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleLabelPostfix = global::CircularGauge.Resource.Attribute.circularScaleLabelPostfix;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleLabelPrefix = global::CircularGauge.Resource.Attribute.circularScaleLabelPrefix;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleLabelTextColor = global::CircularGauge.Resource.Attribute.circularScaleLabelTextColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleLabelTextSize = global::CircularGauge.Resource.Attribute.circularScaleLabelTextSize;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleMajorTickColor = global::CircularGauge.Resource.Attribute.circularScaleMajorTickColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleMajorTickOffset = global::CircularGauge.Resource.Attribute.circularScaleMajorTickOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleMaximumLabels = global::CircularGauge.Resource.Attribute.circularScaleMaximumLabels;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleMinorTickColor = global::CircularGauge.Resource.Attribute.circularScaleMinorTickColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleMinorTickOffset = global::CircularGauge.Resource.Attribute.circularScaleMinorTickOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleMinorTicksPerInterval = global::CircularGauge.Resource.Attribute.circularScaleMinorTicksPerInterval;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleRangeColor = global::CircularGauge.Resource.Attribute.circularScaleRangeColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleRangeEndValue = global::CircularGauge.Resource.Attribute.circularScaleRangeEndValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleRangeOffset = global::CircularGauge.Resource.Attribute.circularScaleRangeOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleRangeStartValue = global::CircularGauge.Resource.Attribute.circularScaleRangeStartValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleShowLabels = global::CircularGauge.Resource.Attribute.circularScaleShowLabels;
			global::Com.Syncfusion.Gauges.Resource.Attribute.circularScaleShowTicks = global::CircularGauge.Resource.Attribute.circularScaleShowTicks;
			global::Com.Syncfusion.Gauges.Resource.Attribute.dimmedSegmentAlpha = global::CircularGauge.Resource.Attribute.dimmedSegmentAlpha;
			global::Com.Syncfusion.Gauges.Resource.Attribute.dimmedSegmentColor = global::CircularGauge.Resource.Attribute.dimmedSegmentColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.markerPointerColor = global::CircularGauge.Resource.Attribute.markerPointerColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.markerPointerHeight = global::CircularGauge.Resource.Attribute.markerPointerHeight;
			global::Com.Syncfusion.Gauges.Resource.Attribute.markerPointerOffset = global::CircularGauge.Resource.Attribute.markerPointerOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.markerPointerValue = global::CircularGauge.Resource.Attribute.markerPointerValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.markerPointerWidth = global::CircularGauge.Resource.Attribute.markerPointerWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.markerShape = global::CircularGauge.Resource.Attribute.markerShape;
			global::Com.Syncfusion.Gauges.Resource.Attribute.maximumLabels = global::CircularGauge.Resource.Attribute.maximumLabels;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerColor = global::CircularGauge.Resource.Attribute.needlePointerColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerKnobColor = global::CircularGauge.Resource.Attribute.needlePointerKnobColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerKnobRadius = global::CircularGauge.Resource.Attribute.needlePointerKnobRadius;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerKnobStrokeColor = global::CircularGauge.Resource.Attribute.needlePointerKnobStrokeColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerKnobStrokeWidth = global::CircularGauge.Resource.Attribute.needlePointerKnobStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerLengthFactor = global::CircularGauge.Resource.Attribute.needlePointerLengthFactor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerTailColor = global::CircularGauge.Resource.Attribute.needlePointerTailColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerTailLengthFactor = global::CircularGauge.Resource.Attribute.needlePointerTailLengthFactor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerTailStrokeColor = global::CircularGauge.Resource.Attribute.needlePointerTailStrokeColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerTailStrokeWidth = global::CircularGauge.Resource.Attribute.needlePointerTailStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerType = global::CircularGauge.Resource.Attribute.needlePointerType;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerValue = global::CircularGauge.Resource.Attribute.needlePointerValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.needlePointerWidth = global::CircularGauge.Resource.Attribute.needlePointerWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeColor = global::CircularGauge.Resource.Attribute.rangeColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeEndValue = global::CircularGauge.Resource.Attribute.rangeEndValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeEndWidth = global::CircularGauge.Resource.Attribute.rangeEndWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeInnerEndOffset = global::CircularGauge.Resource.Attribute.rangeInnerEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeInnerStartOffset = global::CircularGauge.Resource.Attribute.rangeInnerStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeOffset = global::CircularGauge.Resource.Attribute.rangeOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeOuterEndOffset = global::CircularGauge.Resource.Attribute.rangeOuterEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeOuterStartOffset = global::CircularGauge.Resource.Attribute.rangeOuterStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangePointerCap = global::CircularGauge.Resource.Attribute.rangePointerCap;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangePointerColor = global::CircularGauge.Resource.Attribute.rangePointerColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangePointerEndOffset = global::CircularGauge.Resource.Attribute.rangePointerEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangePointerOffset = global::CircularGauge.Resource.Attribute.rangePointerOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangePointerStartOffset = global::CircularGauge.Resource.Attribute.rangePointerStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangePointerStartValue = global::CircularGauge.Resource.Attribute.rangePointerStartValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangePointerValue = global::CircularGauge.Resource.Attribute.rangePointerValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangePointerWidth = global::CircularGauge.Resource.Attribute.rangePointerWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeStartValue = global::CircularGauge.Resource.Attribute.rangeStartValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeStartWidth = global::CircularGauge.Resource.Attribute.rangeStartWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.rangeWidth = global::CircularGauge.Resource.Attribute.rangeWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleAutoAngle = global::CircularGauge.Resource.Attribute.scaleAutoAngle;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleAutoInterval = global::CircularGauge.Resource.Attribute.scaleAutoInterval;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleBarColor = global::CircularGauge.Resource.Attribute.scaleBarColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleBarLength = global::CircularGauge.Resource.Attribute.scaleBarLength;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleBarSize = global::CircularGauge.Resource.Attribute.scaleBarSize;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleCornerRadius = global::CircularGauge.Resource.Attribute.scaleCornerRadius;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleCornerRadiusType = global::CircularGauge.Resource.Attribute.scaleCornerRadiusType;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleDirection = global::CircularGauge.Resource.Attribute.scaleDirection;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleEndAngle = global::CircularGauge.Resource.Attribute.scaleEndAngle;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleEndOffset = global::CircularGauge.Resource.Attribute.scaleEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleEndValue = global::CircularGauge.Resource.Attribute.scaleEndValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleInterval = global::CircularGauge.Resource.Attribute.scaleInterval;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleLabelColor = global::CircularGauge.Resource.Attribute.scaleLabelColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleLabelFontSize = global::CircularGauge.Resource.Attribute.scaleLabelFontSize;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleLabelOffset = global::CircularGauge.Resource.Attribute.scaleLabelOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleLabelPostfix = global::CircularGauge.Resource.Attribute.scaleLabelPostfix;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleLabelPrefix = global::CircularGauge.Resource.Attribute.scaleLabelPrefix;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMajorTickColor = global::CircularGauge.Resource.Attribute.scaleMajorTickColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMajorTickEndOffset = global::CircularGauge.Resource.Attribute.scaleMajorTickEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMajorTickLength = global::CircularGauge.Resource.Attribute.scaleMajorTickLength;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMajorTickOffset = global::CircularGauge.Resource.Attribute.scaleMajorTickOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMajorTickSize = global::CircularGauge.Resource.Attribute.scaleMajorTickSize;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMajorTickStartOffset = global::CircularGauge.Resource.Attribute.scaleMajorTickStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMajorTickStrokeWidth = global::CircularGauge.Resource.Attribute.scaleMajorTickStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMajorTickWidth = global::CircularGauge.Resource.Attribute.scaleMajorTickWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMaximum = global::CircularGauge.Resource.Attribute.scaleMaximum;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMinimum = global::CircularGauge.Resource.Attribute.scaleMinimum;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMinorTickColor = global::CircularGauge.Resource.Attribute.scaleMinorTickColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMinorTickEndOffset = global::CircularGauge.Resource.Attribute.scaleMinorTickEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMinorTickLength = global::CircularGauge.Resource.Attribute.scaleMinorTickLength;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMinorTickOffset = global::CircularGauge.Resource.Attribute.scaleMinorTickOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMinorTickSize = global::CircularGauge.Resource.Attribute.scaleMinorTickSize;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMinorTickStartOffset = global::CircularGauge.Resource.Attribute.scaleMinorTickStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMinorTickStrokeWidth = global::CircularGauge.Resource.Attribute.scaleMinorTickStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMinorTickWidth = global::CircularGauge.Resource.Attribute.scaleMinorTickWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleMinorTicksPerInterval = global::CircularGauge.Resource.Attribute.scaleMinorTicksPerInterval;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleNumberofDecimalDigits = global::CircularGauge.Resource.Attribute.scaleNumberofDecimalDigits;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleOffset = global::CircularGauge.Resource.Attribute.scaleOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleOpposedPosition = global::CircularGauge.Resource.Attribute.scaleOpposedPosition;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleOrientation = global::CircularGauge.Resource.Attribute.scaleOrientation;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleRadiusFactor = global::CircularGauge.Resource.Attribute.scaleRadiusFactor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleRimColor = global::CircularGauge.Resource.Attribute.scaleRimColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleRimWidth = global::CircularGauge.Resource.Attribute.scaleRimWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleShowFirstLabel = global::CircularGauge.Resource.Attribute.scaleShowFirstLabel;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleShowLabels = global::CircularGauge.Resource.Attribute.scaleShowLabels;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleShowLastLabel = global::CircularGauge.Resource.Attribute.scaleShowLastLabel;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleShowRim = global::CircularGauge.Resource.Attribute.scaleShowRim;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleShowTicks = global::CircularGauge.Resource.Attribute.scaleShowTicks;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleStartAngle = global::CircularGauge.Resource.Attribute.scaleStartAngle;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleStartOffset = global::CircularGauge.Resource.Attribute.scaleStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.scaleStartValue = global::CircularGauge.Resource.Attribute.scaleStartValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.segmentStrokeWidth = global::CircularGauge.Resource.Attribute.segmentStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.symbolPointerColor = global::CircularGauge.Resource.Attribute.symbolPointerColor;
			global::Com.Syncfusion.Gauges.Resource.Attribute.symbolPointerOffset = global::CircularGauge.Resource.Attribute.symbolPointerOffset;
			global::Com.Syncfusion.Gauges.Resource.Attribute.symbolPointerStrokeWidth = global::CircularGauge.Resource.Attribute.symbolPointerStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Attribute.symbolPointerValue = global::CircularGauge.Resource.Attribute.symbolPointerValue;
			global::Com.Syncfusion.Gauges.Resource.Attribute.symbolPosition = global::CircularGauge.Resource.Attribute.symbolPosition;
			global::Com.Syncfusion.Gauges.Resource.Dimension.pading_bottom = global::CircularGauge.Resource.Dimension.pading_bottom;
			global::Com.Syncfusion.Gauges.Resource.Dimension.pading_top = global::CircularGauge.Resource.Dimension.pading_top;
			global::Com.Syncfusion.Gauges.Resource.Id.anticlockwise = global::CircularGauge.Resource.Id.anticlockwise;
			global::Com.Syncfusion.Gauges.Resource.Id.away = global::CircularGauge.Resource.Id.away;
			global::Com.Syncfusion.Gauges.Resource.Id.backward = global::CircularGauge.Resource.Id.backward;
			global::Com.Syncfusion.Gauges.Resource.Id.bar = global::CircularGauge.Resource.Id.bar;
			global::Com.Syncfusion.Gauges.Resource.Id.both = global::CircularGauge.Resource.Id.both;
			global::Com.Syncfusion.Gauges.Resource.Id.circle = global::CircularGauge.Resource.Id.circle;
			global::Com.Syncfusion.Gauges.Resource.Id.clockwise = global::CircularGauge.Resource.Id.clockwise;
			global::Com.Syncfusion.Gauges.Resource.Id.diamond = global::CircularGauge.Resource.Id.diamond;
			global::Com.Syncfusion.Gauges.Resource.Id.eightCrossEightDotMatrix = global::CircularGauge.Resource.Id.eightCrossEightDotMatrix;
			global::Com.Syncfusion.Gauges.Resource.Id.eightsegment = global::CircularGauge.Resource.Id.eightsegment;
			global::Com.Syncfusion.Gauges.Resource.Id.end = global::CircularGauge.Resource.Id.end;
			global::Com.Syncfusion.Gauges.Resource.Id.far = global::CircularGauge.Resource.Id.far;
			global::Com.Syncfusion.Gauges.Resource.Id.forward = global::CircularGauge.Resource.Id.forward;
			global::Com.Syncfusion.Gauges.Resource.Id.fourteensegment = global::CircularGauge.Resource.Id.fourteensegment;
			global::Com.Syncfusion.Gauges.Resource.Id.horizontal = global::CircularGauge.Resource.Id.horizontal;
			global::Com.Syncfusion.Gauges.Resource.Id.image = global::CircularGauge.Resource.Id.image;
			global::Com.Syncfusion.Gauges.Resource.Id.invertedTriangle = global::CircularGauge.Resource.Id.invertedTriangle;
			global::Com.Syncfusion.Gauges.Resource.Id.none = global::CircularGauge.Resource.Id.none;
			global::Com.Syncfusion.Gauges.Resource.Id.rectangle = global::CircularGauge.Resource.Id.rectangle;
			global::Com.Syncfusion.Gauges.Resource.Id.rootLayout = global::CircularGauge.Resource.Id.rootLayout;
			global::Com.Syncfusion.Gauges.Resource.Id.segmentFourteen = global::CircularGauge.Resource.Id.segmentFourteen;
			global::Com.Syncfusion.Gauges.Resource.Id.segmentSeven = global::CircularGauge.Resource.Id.segmentSeven;
			global::Com.Syncfusion.Gauges.Resource.Id.segmentSixteen = global::CircularGauge.Resource.Id.segmentSixteen;
			global::Com.Syncfusion.Gauges.Resource.Id.sevensegment = global::CircularGauge.Resource.Id.sevensegment;
			global::Com.Syncfusion.Gauges.Resource.Id.sixteensegment = global::CircularGauge.Resource.Id.sixteensegment;
			global::Com.Syncfusion.Gauges.Resource.Id.start = global::CircularGauge.Resource.Id.start;
			global::Com.Syncfusion.Gauges.Resource.Id.triangle = global::CircularGauge.Resource.Id.triangle;
			global::Com.Syncfusion.Gauges.Resource.Id.vertical = global::CircularGauge.Resource.Id.vertical;
			global::Com.Syncfusion.Gauges.Resource.Layout.circulargauge_layout = global::CircularGauge.Resource.Layout.circulargauge_layout;
			global::Com.Syncfusion.Gauges.Resource.Layout.digitalgauge_layout = global::CircularGauge.Resource.Layout.digitalgauge_layout;
			global::Com.Syncfusion.Gauges.Resource.String.ApplicationName = global::CircularGauge.Resource.String.ApplicationName;
			global::Com.Syncfusion.Gauges.Resource.String.Hello = global::CircularGauge.Resource.String.Hello;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge = global::CircularGauge.Resource.Styleable.SfCircularGauge;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularGaugeScaleDirection = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularGaugeScaleDirection;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleInterval = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleInterval;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleLabelOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleLabelOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleLabelPostfix = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleLabelPostfix;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleLabelPrefix = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleLabelPrefix;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleLabelTextColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleLabelTextColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleLabelTextSize = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleLabelTextSize;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleMajorTickColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleMajorTickColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleMajorTickOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleMajorTickOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleMaximumLabels = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleMaximumLabels;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleMinorTickColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleMinorTickColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleMinorTickOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleMinorTickOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleMinorTicksPerInterval = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleMinorTicksPerInterval;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleRangeColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleRangeColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleRangeEndValue = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleRangeEndValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleRangeOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleRangeOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleRangeStartValue = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleRangeStartValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleShowLabels = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleShowLabels;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_circularScaleShowTicks = global::CircularGauge.Resource.Styleable.SfCircularGauge_circularScaleShowTicks;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_markerPointerColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_markerPointerColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_markerPointerHeight = global::CircularGauge.Resource.Styleable.SfCircularGauge_markerPointerHeight;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_markerPointerOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_markerPointerOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_markerPointerValue = global::CircularGauge.Resource.Styleable.SfCircularGauge_markerPointerValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_markerPointerWidth = global::CircularGauge.Resource.Styleable.SfCircularGauge_markerPointerWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_markerShape = global::CircularGauge.Resource.Styleable.SfCircularGauge_markerShape;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerKnobColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerKnobColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerKnobRadius = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerKnobRadius;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerKnobStrokeColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerKnobStrokeColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerKnobStrokeWidth = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerKnobStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerLengthFactor = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerLengthFactor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerTailColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerTailColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerTailLengthFactor = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerTailLengthFactor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerTailStrokeColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerTailStrokeColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerTailStrokeWidth = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerTailStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerType = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerType;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerValue = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_needlePointerWidth = global::CircularGauge.Resource.Styleable.SfCircularGauge_needlePointerWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangeInnerEndOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangeInnerEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangeInnerStartOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangeInnerStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangeOuterEndOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangeOuterEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangeOuterStartOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangeOuterStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangePointerCap = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangePointerCap;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangePointerColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangePointerColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangePointerEndOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangePointerEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangePointerOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangePointerOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangePointerStartOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangePointerStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangePointerStartValue = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangePointerStartValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangePointerValue = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangePointerValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangePointerWidth = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangePointerWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_rangeWidth = global::CircularGauge.Resource.Styleable.SfCircularGauge_rangeWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleAutoAngle = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleAutoAngle;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleAutoInterval = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleAutoInterval;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleEndAngle = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleEndAngle;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleEndOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleEndValue = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleEndValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleMajorTickEndOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleMajorTickEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleMajorTickSize = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleMajorTickSize;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleMajorTickStartOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleMajorTickStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleMajorTickWidth = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleMajorTickWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleMinorTickEndOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleMinorTickEndOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleMinorTickSize = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleMinorTickSize;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleMinorTickStartOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleMinorTickStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleMinorTickWidth = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleMinorTickWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleNumberofDecimalDigits = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleNumberofDecimalDigits;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleRadiusFactor = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleRadiusFactor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleRimColor = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleRimColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleRimWidth = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleRimWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleShowFirstLabel = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleShowFirstLabel;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleShowLastLabel = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleShowLastLabel;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleShowRim = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleShowRim;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleStartAngle = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleStartAngle;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleStartOffset = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleStartOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfCircularGauge_scaleStartValue = global::CircularGauge.Resource.Styleable.SfCircularGauge_scaleStartValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfDigitalGauge = global::CircularGauge.Resource.Styleable.SfDigitalGauge;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfDigitalGauge_characterHeight = global::CircularGauge.Resource.Styleable.SfDigitalGauge_characterHeight;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfDigitalGauge_characterSpacing = global::CircularGauge.Resource.Styleable.SfDigitalGauge_characterSpacing;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfDigitalGauge_characterStrokeColor = global::CircularGauge.Resource.Styleable.SfDigitalGauge_characterStrokeColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfDigitalGauge_characterType = global::CircularGauge.Resource.Styleable.SfDigitalGauge_characterType;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfDigitalGauge_characterWidth = global::CircularGauge.Resource.Styleable.SfDigitalGauge_characterWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfDigitalGauge_dimmedSegmentAlpha = global::CircularGauge.Resource.Styleable.SfDigitalGauge_dimmedSegmentAlpha;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfDigitalGauge_dimmedSegmentColor = global::CircularGauge.Resource.Styleable.SfDigitalGauge_dimmedSegmentColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfDigitalGauge_segmentStrokeWidth = global::CircularGauge.Resource.Styleable.SfDigitalGauge_segmentStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge = global::CircularGauge.Resource.Styleable.SfLinearGauge;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_barPointerColor = global::CircularGauge.Resource.Styleable.SfLinearGauge_barPointerColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_barPointerCornerRadius = global::CircularGauge.Resource.Styleable.SfLinearGauge_barPointerCornerRadius;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_barPointerCornerRadiusType = global::CircularGauge.Resource.Styleable.SfLinearGauge_barPointerCornerRadiusType;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_barPointerStrokeWidth = global::CircularGauge.Resource.Styleable.SfLinearGauge_barPointerStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_barPointerValue = global::CircularGauge.Resource.Styleable.SfLinearGauge_barPointerValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_maximumLabels = global::CircularGauge.Resource.Styleable.SfLinearGauge_maximumLabels;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_rangeColor = global::CircularGauge.Resource.Styleable.SfLinearGauge_rangeColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_rangeEndValue = global::CircularGauge.Resource.Styleable.SfLinearGauge_rangeEndValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_rangeEndWidth = global::CircularGauge.Resource.Styleable.SfLinearGauge_rangeEndWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_rangeOffset = global::CircularGauge.Resource.Styleable.SfLinearGauge_rangeOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_rangeStartValue = global::CircularGauge.Resource.Styleable.SfLinearGauge_rangeStartValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_rangeStartWidth = global::CircularGauge.Resource.Styleable.SfLinearGauge_rangeStartWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleBarColor = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleBarColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleBarLength = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleBarLength;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleBarSize = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleBarSize;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleCornerRadius = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleCornerRadius;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleCornerRadiusType = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleCornerRadiusType;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleDirection = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleDirection;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleInterval = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleInterval;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleLabelColor = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleLabelColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleLabelFontSize = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleLabelFontSize;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleLabelOffset = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleLabelOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleLabelPostfix = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleLabelPostfix;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleLabelPrefix = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleLabelPrefix;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMajorTickColor = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMajorTickColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMajorTickLength = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMajorTickLength;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMajorTickOffset = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMajorTickOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMajorTickStrokeWidth = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMajorTickStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMaximum = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMaximum;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMinimum = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMinimum;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMinorTickColor = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMinorTickColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMinorTickLength = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMinorTickLength;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMinorTickOffset = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMinorTickOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMinorTickStrokeWidth = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMinorTickStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleMinorTicksPerInterval = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleMinorTicksPerInterval;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleOffset = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleOpposedPosition = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleOpposedPosition;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleOrientation = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleOrientation;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleShowLabels = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleShowLabels;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_scaleShowTicks = global::CircularGauge.Resource.Styleable.SfLinearGauge_scaleShowTicks;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_symbolPointerColor = global::CircularGauge.Resource.Styleable.SfLinearGauge_symbolPointerColor;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_symbolPointerOffset = global::CircularGauge.Resource.Styleable.SfLinearGauge_symbolPointerOffset;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_symbolPointerStrokeWidth = global::CircularGauge.Resource.Styleable.SfLinearGauge_symbolPointerStrokeWidth;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_symbolPointerValue = global::CircularGauge.Resource.Styleable.SfLinearGauge_symbolPointerValue;
			global::Com.Syncfusion.Gauges.Resource.Styleable.SfLinearGauge_symbolPosition = global::CircularGauge.Resource.Styleable.SfLinearGauge_symbolPosition;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01006d
			public const int barPointerColor = 2130772077;
			
			// aapt resource value: 0x7f010070
			public const int barPointerCornerRadius = 2130772080;
			
			// aapt resource value: 0x7f01006f
			public const int barPointerCornerRadiusType = 2130772079;
			
			// aapt resource value: 0x7f01006e
			public const int barPointerStrokeWidth = 2130772078;
			
			// aapt resource value: 0x7f01006c
			public const int barPointerValue = 2130772076;
			
			// aapt resource value: 0x7f010078
			public const int characterHeight = 2130772088;
			
			// aapt resource value: 0x7f010079
			public const int characterSpacing = 2130772089;
			
			// aapt resource value: 0x7f010077
			public const int characterStrokeColor = 2130772087;
			
			// aapt resource value: 0x7f01007e
			public const int characterType = 2130772094;
			
			// aapt resource value: 0x7f01007a
			public const int characterWidth = 2130772090;
			
			// aapt resource value: 0x7f010006
			public const int circularGaugeScaleDirection = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int circularScaleInterval = 2130771972;
			
			// aapt resource value: 0x7f01000f
			public const int circularScaleLabelOffset = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public const int circularScaleLabelPostfix = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int circularScaleLabelPrefix = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int circularScaleLabelTextColor = 2130771984;
			
			// aapt resource value: 0x7f01000e
			public const int circularScaleLabelTextSize = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int circularScaleMajorTickColor = 2130771986;
			
			// aapt resource value: 0x7f010014
			public const int circularScaleMajorTickOffset = 2130771988;
			
			// aapt resource value: 0x7f010020
			public const int circularScaleMaximumLabels = 2130772000;
			
			// aapt resource value: 0x7f010018
			public const int circularScaleMinorTickColor = 2130771992;
			
			// aapt resource value: 0x7f01001a
			public const int circularScaleMinorTickOffset = 2130771994;
			
			// aapt resource value: 0x7f01001f
			public const int circularScaleMinorTicksPerInterval = 2130771999;
			
			// aapt resource value: 0x7f01002a
			public const int circularScaleRangeColor = 2130772010;
			
			// aapt resource value: 0x7f010027
			public const int circularScaleRangeEndValue = 2130772007;
			
			// aapt resource value: 0x7f010029
			public const int circularScaleRangeOffset = 2130772009;
			
			// aapt resource value: 0x7f010026
			public const int circularScaleRangeStartValue = 2130772006;
			
			// aapt resource value: 0x7f010021
			public const int circularScaleShowLabels = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int circularScaleShowTicks = 2130772002;
			
			// aapt resource value: 0x7f01007d
			public const int dimmedSegmentAlpha = 2130772093;
			
			// aapt resource value: 0x7f01007c
			public const int dimmedSegmentColor = 2130772092;
			
			// aapt resource value: 0x7f010046
			public const int markerPointerColor = 2130772038;
			
			// aapt resource value: 0x7f010047
			public const int markerPointerHeight = 2130772039;
			
			// aapt resource value: 0x7f010049
			public const int markerPointerOffset = 2130772041;
			
			// aapt resource value: 0x7f010044
			public const int markerPointerValue = 2130772036;
			
			// aapt resource value: 0x7f010048
			public const int markerPointerWidth = 2130772040;
			
			// aapt resource value: 0x7f010045
			public const int markerShape = 2130772037;
			
			// aapt resource value: 0x7f010060
			public const int maximumLabels = 2130772064;
			
			// aapt resource value: 0x7f010031
			public const int needlePointerColor = 2130772017;
			
			// aapt resource value: 0x7f010036
			public const int needlePointerKnobColor = 2130772022;
			
			// aapt resource value: 0x7f010034
			public const int needlePointerKnobRadius = 2130772020;
			
			// aapt resource value: 0x7f010035
			public const int needlePointerKnobStrokeColor = 2130772021;
			
			// aapt resource value: 0x7f010037
			public const int needlePointerKnobStrokeWidth = 2130772023;
			
			// aapt resource value: 0x7f010033
			public const int needlePointerLengthFactor = 2130772019;
			
			// aapt resource value: 0x7f010038
			public const int needlePointerTailColor = 2130772024;
			
			// aapt resource value: 0x7f010039
			public const int needlePointerTailLengthFactor = 2130772025;
			
			// aapt resource value: 0x7f01003b
			public const int needlePointerTailStrokeColor = 2130772027;
			
			// aapt resource value: 0x7f01003a
			public const int needlePointerTailStrokeWidth = 2130772026;
			
			// aapt resource value: 0x7f010030
			public const int needlePointerType = 2130772016;
			
			// aapt resource value: 0x7f01002f
			public const int needlePointerValue = 2130772015;
			
			// aapt resource value: 0x7f010032
			public const int needlePointerWidth = 2130772018;
			
			// aapt resource value: 0x7f01006b
			public const int rangeColor = 2130772075;
			
			// aapt resource value: 0x7f010067
			public const int rangeEndValue = 2130772071;
			
			// aapt resource value: 0x7f010069
			public const int rangeEndWidth = 2130772073;
			
			// aapt resource value: 0x7f01002c
			public const int rangeInnerEndOffset = 2130772012;
			
			// aapt resource value: 0x7f01002b
			public const int rangeInnerStartOffset = 2130772011;
			
			// aapt resource value: 0x7f01006a
			public const int rangeOffset = 2130772074;
			
			// aapt resource value: 0x7f01002e
			public const int rangeOuterEndOffset = 2130772014;
			
			// aapt resource value: 0x7f01002d
			public const int rangeOuterStartOffset = 2130772013;
			
			// aapt resource value: 0x7f010043
			public const int rangePointerCap = 2130772035;
			
			// aapt resource value: 0x7f01003e
			public const int rangePointerColor = 2130772030;
			
			// aapt resource value: 0x7f010042
			public const int rangePointerEndOffset = 2130772034;
			
			// aapt resource value: 0x7f010040
			public const int rangePointerOffset = 2130772032;
			
			// aapt resource value: 0x7f010041
			public const int rangePointerStartOffset = 2130772033;
			
			// aapt resource value: 0x7f01003c
			public const int rangePointerStartValue = 2130772028;
			
			// aapt resource value: 0x7f01003d
			public const int rangePointerValue = 2130772029;
			
			// aapt resource value: 0x7f01003f
			public const int rangePointerWidth = 2130772031;
			
			// aapt resource value: 0x7f010066
			public const int rangeStartValue = 2130772070;
			
			// aapt resource value: 0x7f010068
			public const int rangeStartWidth = 2130772072;
			
			// aapt resource value: 0x7f010028
			public const int rangeWidth = 2130772008;
			
			// aapt resource value: 0x7f01000b
			public const int scaleAutoAngle = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int scaleAutoInterval = 2130771973;
			
			// aapt resource value: 0x7f010055
			public const int scaleBarColor = 2130772053;
			
			// aapt resource value: 0x7f010057
			public const int scaleBarLength = 2130772055;
			
			// aapt resource value: 0x7f010056
			public const int scaleBarSize = 2130772054;
			
			// aapt resource value: 0x7f010064
			public const int scaleCornerRadius = 2130772068;
			
			// aapt resource value: 0x7f010063
			public const int scaleCornerRadiusType = 2130772067;
			
			// aapt resource value: 0x7f010062
			public const int scaleDirection = 2130772066;
			
			// aapt resource value: 0x7f010001
			public const int scaleEndAngle = 2130771969;
			
			// aapt resource value: 0x7f01000a
			public const int scaleEndOffset = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int scaleEndValue = 2130771971;
			
			// aapt resource value: 0x7f01004c
			public const int scaleInterval = 2130772044;
			
			// aapt resource value: 0x7f010058
			public const int scaleLabelColor = 2130772056;
			
			// aapt resource value: 0x7f01005b
			public const int scaleLabelFontSize = 2130772059;
			
			// aapt resource value: 0x7f01005c
			public const int scaleLabelOffset = 2130772060;
			
			// aapt resource value: 0x7f01005a
			public const int scaleLabelPostfix = 2130772058;
			
			// aapt resource value: 0x7f010059
			public const int scaleLabelPrefix = 2130772057;
			
			// aapt resource value: 0x7f01004e
			public const int scaleMajorTickColor = 2130772046;
			
			// aapt resource value: 0x7f010016
			public const int scaleMajorTickEndOffset = 2130771990;
			
			// aapt resource value: 0x7f01004d
			public const int scaleMajorTickLength = 2130772045;
			
			// aapt resource value: 0x7f010050
			public const int scaleMajorTickOffset = 2130772048;
			
			// aapt resource value: 0x7f010011
			public const int scaleMajorTickSize = 2130771985;
			
			// aapt resource value: 0x7f010015
			public const int scaleMajorTickStartOffset = 2130771989;
			
			// aapt resource value: 0x7f01004f
			public const int scaleMajorTickStrokeWidth = 2130772047;
			
			// aapt resource value: 0x7f010013
			public const int scaleMajorTickWidth = 2130771987;
			
			// aapt resource value: 0x7f01004b
			public const int scaleMaximum = 2130772043;
			
			// aapt resource value: 0x7f01004a
			public const int scaleMinimum = 2130772042;
			
			// aapt resource value: 0x7f010052
			public const int scaleMinorTickColor = 2130772050;
			
			// aapt resource value: 0x7f01001c
			public const int scaleMinorTickEndOffset = 2130771996;
			
			// aapt resource value: 0x7f010051
			public const int scaleMinorTickLength = 2130772049;
			
			// aapt resource value: 0x7f010054
			public const int scaleMinorTickOffset = 2130772052;
			
			// aapt resource value: 0x7f010017
			public const int scaleMinorTickSize = 2130771991;
			
			// aapt resource value: 0x7f01001b
			public const int scaleMinorTickStartOffset = 2130771995;
			
			// aapt resource value: 0x7f010053
			public const int scaleMinorTickStrokeWidth = 2130772051;
			
			// aapt resource value: 0x7f010019
			public const int scaleMinorTickWidth = 2130771993;
			
			// aapt resource value: 0x7f01005f
			public const int scaleMinorTicksPerInterval = 2130772063;
			
			// aapt resource value: 0x7f010025
			public const int scaleNumberofDecimalDigits = 2130772005;
			
			// aapt resource value: 0x7f010065
			public const int scaleOffset = 2130772069;
			
			// aapt resource value: 0x7f010061
			public const int scaleOpposedPosition = 2130772065;
			
			// aapt resource value: 0x7f010076
			public const int scaleOrientation = 2130772086;
			
			// aapt resource value: 0x7f010024
			public const int scaleRadiusFactor = 2130772004;
			
			// aapt resource value: 0x7f01001d
			public const int scaleRimColor = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int scaleRimWidth = 2130771998;
			
			// aapt resource value: 0x7f010007
			public const int scaleShowFirstLabel = 2130771975;
			
			// aapt resource value: 0x7f01005d
			public const int scaleShowLabels = 2130772061;
			
			// aapt resource value: 0x7f010008
			public const int scaleShowLastLabel = 2130771976;
			
			// aapt resource value: 0x7f010023
			public const int scaleShowRim = 2130772003;
			
			// aapt resource value: 0x7f01005e
			public const int scaleShowTicks = 2130772062;
			
			// aapt resource value: 0x7f010000
			public const int scaleStartAngle = 2130771968;
			
			// aapt resource value: 0x7f010009
			public const int scaleStartOffset = 2130771977;
			
			// aapt resource value: 0x7f010002
			public const int scaleStartValue = 2130771970;
			
			// aapt resource value: 0x7f01007b
			public const int segmentStrokeWidth = 2130772091;
			
			// aapt resource value: 0x7f010072
			public const int symbolPointerColor = 2130772082;
			
			// aapt resource value: 0x7f010074
			public const int symbolPointerOffset = 2130772084;
			
			// aapt resource value: 0x7f010073
			public const int symbolPointerStrokeWidth = 2130772083;
			
			// aapt resource value: 0x7f010071
			public const int symbolPointerValue = 2130772081;
			
			// aapt resource value: 0x7f010075
			public const int symbolPosition = 2130772085;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030001
			public const int pading_bottom = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int pading_top = 2130903040;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int anticlockwise = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int away = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int backward = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int bar = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int both = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int circle = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int clockwise = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int diamond = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int eightCrossEightDotMatrix = 2131034131;
			
			// aapt resource value: 0x7f050019
			public const int eightsegment = 2131034137;
			
			// aapt resource value: 0x7f050005
			public const int end = 2131034117;
			
			// aapt resource value: 0x7f050010
			public const int far = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int forward = 2131034126;
			
			// aapt resource value: 0x7f05001a
			public const int fourteensegment = 2131034138;
			
			// aapt resource value: 0x7f050011
			public const int horizontal = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int image = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int invertedTriangle = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int none = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int rectangle = 2131034124;
			
			// aapt resource value: 0x7f050017
			public const int rootLayout = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int segmentFourteen = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int segmentSeven = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int segmentSixteen = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int sevensegment = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int sixteensegment = 2131034139;
			
			// aapt resource value: 0x7f050007
			public const int start = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int triangle = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int vertical = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int circulargauge_layout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int digitalgauge_layout = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SfCircularGauge = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041};
			
			// aapt resource value: 6
			public const int SfCircularGauge_circularGaugeScaleDirection = 6;
			
			// aapt resource value: 4
			public const int SfCircularGauge_circularScaleInterval = 4;
			
			// aapt resource value: 15
			public const int SfCircularGauge_circularScaleLabelOffset = 15;
			
			// aapt resource value: 13
			public const int SfCircularGauge_circularScaleLabelPostfix = 13;
			
			// aapt resource value: 12
			public const int SfCircularGauge_circularScaleLabelPrefix = 12;
			
			// aapt resource value: 16
			public const int SfCircularGauge_circularScaleLabelTextColor = 16;
			
			// aapt resource value: 14
			public const int SfCircularGauge_circularScaleLabelTextSize = 14;
			
			// aapt resource value: 18
			public const int SfCircularGauge_circularScaleMajorTickColor = 18;
			
			// aapt resource value: 20
			public const int SfCircularGauge_circularScaleMajorTickOffset = 20;
			
			// aapt resource value: 32
			public const int SfCircularGauge_circularScaleMaximumLabels = 32;
			
			// aapt resource value: 24
			public const int SfCircularGauge_circularScaleMinorTickColor = 24;
			
			// aapt resource value: 26
			public const int SfCircularGauge_circularScaleMinorTickOffset = 26;
			
			// aapt resource value: 31
			public const int SfCircularGauge_circularScaleMinorTicksPerInterval = 31;
			
			// aapt resource value: 42
			public const int SfCircularGauge_circularScaleRangeColor = 42;
			
			// aapt resource value: 39
			public const int SfCircularGauge_circularScaleRangeEndValue = 39;
			
			// aapt resource value: 41
			public const int SfCircularGauge_circularScaleRangeOffset = 41;
			
			// aapt resource value: 38
			public const int SfCircularGauge_circularScaleRangeStartValue = 38;
			
			// aapt resource value: 33
			public const int SfCircularGauge_circularScaleShowLabels = 33;
			
			// aapt resource value: 34
			public const int SfCircularGauge_circularScaleShowTicks = 34;
			
			// aapt resource value: 70
			public const int SfCircularGauge_markerPointerColor = 70;
			
			// aapt resource value: 71
			public const int SfCircularGauge_markerPointerHeight = 71;
			
			// aapt resource value: 73
			public const int SfCircularGauge_markerPointerOffset = 73;
			
			// aapt resource value: 68
			public const int SfCircularGauge_markerPointerValue = 68;
			
			// aapt resource value: 72
			public const int SfCircularGauge_markerPointerWidth = 72;
			
			// aapt resource value: 69
			public const int SfCircularGauge_markerShape = 69;
			
			// aapt resource value: 49
			public const int SfCircularGauge_needlePointerColor = 49;
			
			// aapt resource value: 54
			public const int SfCircularGauge_needlePointerKnobColor = 54;
			
			// aapt resource value: 52
			public const int SfCircularGauge_needlePointerKnobRadius = 52;
			
			// aapt resource value: 53
			public const int SfCircularGauge_needlePointerKnobStrokeColor = 53;
			
			// aapt resource value: 55
			public const int SfCircularGauge_needlePointerKnobStrokeWidth = 55;
			
			// aapt resource value: 51
			public const int SfCircularGauge_needlePointerLengthFactor = 51;
			
			// aapt resource value: 56
			public const int SfCircularGauge_needlePointerTailColor = 56;
			
			// aapt resource value: 57
			public const int SfCircularGauge_needlePointerTailLengthFactor = 57;
			
			// aapt resource value: 59
			public const int SfCircularGauge_needlePointerTailStrokeColor = 59;
			
			// aapt resource value: 58
			public const int SfCircularGauge_needlePointerTailStrokeWidth = 58;
			
			// aapt resource value: 48
			public const int SfCircularGauge_needlePointerType = 48;
			
			// aapt resource value: 47
			public const int SfCircularGauge_needlePointerValue = 47;
			
			// aapt resource value: 50
			public const int SfCircularGauge_needlePointerWidth = 50;
			
			// aapt resource value: 44
			public const int SfCircularGauge_rangeInnerEndOffset = 44;
			
			// aapt resource value: 43
			public const int SfCircularGauge_rangeInnerStartOffset = 43;
			
			// aapt resource value: 46
			public const int SfCircularGauge_rangeOuterEndOffset = 46;
			
			// aapt resource value: 45
			public const int SfCircularGauge_rangeOuterStartOffset = 45;
			
			// aapt resource value: 67
			public const int SfCircularGauge_rangePointerCap = 67;
			
			// aapt resource value: 62
			public const int SfCircularGauge_rangePointerColor = 62;
			
			// aapt resource value: 66
			public const int SfCircularGauge_rangePointerEndOffset = 66;
			
			// aapt resource value: 64
			public const int SfCircularGauge_rangePointerOffset = 64;
			
			// aapt resource value: 65
			public const int SfCircularGauge_rangePointerStartOffset = 65;
			
			// aapt resource value: 60
			public const int SfCircularGauge_rangePointerStartValue = 60;
			
			// aapt resource value: 61
			public const int SfCircularGauge_rangePointerValue = 61;
			
			// aapt resource value: 63
			public const int SfCircularGauge_rangePointerWidth = 63;
			
			// aapt resource value: 40
			public const int SfCircularGauge_rangeWidth = 40;
			
			// aapt resource value: 11
			public const int SfCircularGauge_scaleAutoAngle = 11;
			
			// aapt resource value: 5
			public const int SfCircularGauge_scaleAutoInterval = 5;
			
			// aapt resource value: 1
			public const int SfCircularGauge_scaleEndAngle = 1;
			
			// aapt resource value: 10
			public const int SfCircularGauge_scaleEndOffset = 10;
			
			// aapt resource value: 3
			public const int SfCircularGauge_scaleEndValue = 3;
			
			// aapt resource value: 22
			public const int SfCircularGauge_scaleMajorTickEndOffset = 22;
			
			// aapt resource value: 17
			public const int SfCircularGauge_scaleMajorTickSize = 17;
			
			// aapt resource value: 21
			public const int SfCircularGauge_scaleMajorTickStartOffset = 21;
			
			// aapt resource value: 19
			public const int SfCircularGauge_scaleMajorTickWidth = 19;
			
			// aapt resource value: 28
			public const int SfCircularGauge_scaleMinorTickEndOffset = 28;
			
			// aapt resource value: 23
			public const int SfCircularGauge_scaleMinorTickSize = 23;
			
			// aapt resource value: 27
			public const int SfCircularGauge_scaleMinorTickStartOffset = 27;
			
			// aapt resource value: 25
			public const int SfCircularGauge_scaleMinorTickWidth = 25;
			
			// aapt resource value: 37
			public const int SfCircularGauge_scaleNumberofDecimalDigits = 37;
			
			// aapt resource value: 36
			public const int SfCircularGauge_scaleRadiusFactor = 36;
			
			// aapt resource value: 29
			public const int SfCircularGauge_scaleRimColor = 29;
			
			// aapt resource value: 30
			public const int SfCircularGauge_scaleRimWidth = 30;
			
			// aapt resource value: 7
			public const int SfCircularGauge_scaleShowFirstLabel = 7;
			
			// aapt resource value: 8
			public const int SfCircularGauge_scaleShowLastLabel = 8;
			
			// aapt resource value: 35
			public const int SfCircularGauge_scaleShowRim = 35;
			
			// aapt resource value: 0
			public const int SfCircularGauge_scaleStartAngle = 0;
			
			// aapt resource value: 9
			public const int SfCircularGauge_scaleStartOffset = 9;
			
			// aapt resource value: 2
			public const int SfCircularGauge_scaleStartValue = 2;
			
			public static int[] SfDigitalGauge = new int[] {
					2130772087,
					2130772088,
					2130772089,
					2130772090,
					2130772091,
					2130772092,
					2130772093,
					2130772094};
			
			// aapt resource value: 1
			public const int SfDigitalGauge_characterHeight = 1;
			
			// aapt resource value: 2
			public const int SfDigitalGauge_characterSpacing = 2;
			
			// aapt resource value: 0
			public const int SfDigitalGauge_characterStrokeColor = 0;
			
			// aapt resource value: 7
			public const int SfDigitalGauge_characterType = 7;
			
			// aapt resource value: 3
			public const int SfDigitalGauge_characterWidth = 3;
			
			// aapt resource value: 6
			public const int SfDigitalGauge_dimmedSegmentAlpha = 6;
			
			// aapt resource value: 5
			public const int SfDigitalGauge_dimmedSegmentColor = 5;
			
			// aapt resource value: 4
			public const int SfDigitalGauge_segmentStrokeWidth = 4;
			
			public static int[] SfLinearGauge = new int[] {
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050,
					2130772051,
					2130772052,
					2130772053,
					2130772054,
					2130772055,
					2130772056,
					2130772057,
					2130772058,
					2130772059,
					2130772060,
					2130772061,
					2130772062,
					2130772063,
					2130772064,
					2130772065,
					2130772066,
					2130772067,
					2130772068,
					2130772069,
					2130772070,
					2130772071,
					2130772072,
					2130772073,
					2130772074,
					2130772075,
					2130772076,
					2130772077,
					2130772078,
					2130772079,
					2130772080,
					2130772081,
					2130772082,
					2130772083,
					2130772084,
					2130772085,
					2130772086};
			
			// aapt resource value: 35
			public const int SfLinearGauge_barPointerColor = 35;
			
			// aapt resource value: 38
			public const int SfLinearGauge_barPointerCornerRadius = 38;
			
			// aapt resource value: 37
			public const int SfLinearGauge_barPointerCornerRadiusType = 37;
			
			// aapt resource value: 36
			public const int SfLinearGauge_barPointerStrokeWidth = 36;
			
			// aapt resource value: 34
			public const int SfLinearGauge_barPointerValue = 34;
			
			// aapt resource value: 22
			public const int SfLinearGauge_maximumLabels = 22;
			
			// aapt resource value: 33
			public const int SfLinearGauge_rangeColor = 33;
			
			// aapt resource value: 29
			public const int SfLinearGauge_rangeEndValue = 29;
			
			// aapt resource value: 31
			public const int SfLinearGauge_rangeEndWidth = 31;
			
			// aapt resource value: 32
			public const int SfLinearGauge_rangeOffset = 32;
			
			// aapt resource value: 28
			public const int SfLinearGauge_rangeStartValue = 28;
			
			// aapt resource value: 30
			public const int SfLinearGauge_rangeStartWidth = 30;
			
			// aapt resource value: 11
			public const int SfLinearGauge_scaleBarColor = 11;
			
			// aapt resource value: 13
			public const int SfLinearGauge_scaleBarLength = 13;
			
			// aapt resource value: 12
			public const int SfLinearGauge_scaleBarSize = 12;
			
			// aapt resource value: 26
			public const int SfLinearGauge_scaleCornerRadius = 26;
			
			// aapt resource value: 25
			public const int SfLinearGauge_scaleCornerRadiusType = 25;
			
			// aapt resource value: 24
			public const int SfLinearGauge_scaleDirection = 24;
			
			// aapt resource value: 2
			public const int SfLinearGauge_scaleInterval = 2;
			
			// aapt resource value: 14
			public const int SfLinearGauge_scaleLabelColor = 14;
			
			// aapt resource value: 17
			public const int SfLinearGauge_scaleLabelFontSize = 17;
			
			// aapt resource value: 18
			public const int SfLinearGauge_scaleLabelOffset = 18;
			
			// aapt resource value: 16
			public const int SfLinearGauge_scaleLabelPostfix = 16;
			
			// aapt resource value: 15
			public const int SfLinearGauge_scaleLabelPrefix = 15;
			
			// aapt resource value: 4
			public const int SfLinearGauge_scaleMajorTickColor = 4;
			
			// aapt resource value: 3
			public const int SfLinearGauge_scaleMajorTickLength = 3;
			
			// aapt resource value: 6
			public const int SfLinearGauge_scaleMajorTickOffset = 6;
			
			// aapt resource value: 5
			public const int SfLinearGauge_scaleMajorTickStrokeWidth = 5;
			
			// aapt resource value: 1
			public const int SfLinearGauge_scaleMaximum = 1;
			
			// aapt resource value: 0
			public const int SfLinearGauge_scaleMinimum = 0;
			
			// aapt resource value: 8
			public const int SfLinearGauge_scaleMinorTickColor = 8;
			
			// aapt resource value: 7
			public const int SfLinearGauge_scaleMinorTickLength = 7;
			
			// aapt resource value: 10
			public const int SfLinearGauge_scaleMinorTickOffset = 10;
			
			// aapt resource value: 9
			public const int SfLinearGauge_scaleMinorTickStrokeWidth = 9;
			
			// aapt resource value: 21
			public const int SfLinearGauge_scaleMinorTicksPerInterval = 21;
			
			// aapt resource value: 27
			public const int SfLinearGauge_scaleOffset = 27;
			
			// aapt resource value: 23
			public const int SfLinearGauge_scaleOpposedPosition = 23;
			
			// aapt resource value: 44
			public const int SfLinearGauge_scaleOrientation = 44;
			
			// aapt resource value: 19
			public const int SfLinearGauge_scaleShowLabels = 19;
			
			// aapt resource value: 20
			public const int SfLinearGauge_scaleShowTicks = 20;
			
			// aapt resource value: 40
			public const int SfLinearGauge_symbolPointerColor = 40;
			
			// aapt resource value: 42
			public const int SfLinearGauge_symbolPointerOffset = 42;
			
			// aapt resource value: 41
			public const int SfLinearGauge_symbolPointerStrokeWidth = 41;
			
			// aapt resource value: 39
			public const int SfLinearGauge_symbolPointerValue = 39;
			
			// aapt resource value: 43
			public const int SfLinearGauge_symbolPosition = 43;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
